### ISSUE TITLE
How to use with AppBarButton.Icon?

### ISSUE THREAD

**Issue by dpaulino** [yoshiask/FluentSystemIconsUWP#1]
I'm trying to do this:
![image](https://user-images.githubusercontent.com/7649589/86716130-c149cd00-bfd5-11ea-95f2-ed1c3c5d6c83.png)

But the compiler complains that AppBarButton.Icon requires types derived from `IconElement`

**Comment by dpaulino** [comment]
Silly me. Apparently I have lost my ability to read. I see there are already instructions in the readme. My bad, and thanks Yoshi :)

![image](https://user-images.githubusercontent.com/7649589/86716615-374e3400-bfd6-11ea-8523-8cac083e6f8f.png)

**Comment by yoshiask** [comment]
No problem, I'm hope you find this library useful!
