### ISSUE TITLE
'Cut' icon?

### ISSUE THREAD

**Issue by goranalkovic** [yoshiask/FluentSystemIconsUWP#3]
Hi,
I can't seem to find the 'Cut' icon in the list of available ones, even thought it's on the official Fluent Icons list.

**Comment by yoshiask** [comment]
The generator only uses icons that have a 24px variant. The 'cut' icon only has a 20px variant. This could be fixed in a future release by using fallback sizes.

**Comment by yoshiask** [comment]
@goranalkovic This issues should be fixed in the latest release (1.1.59.0). Please let me know if it works!

**Comment by goranalkovic** [comment]
Working fine now! Thanks!
